spring:
  profiles: mail
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: abir835.bs23@gmail.com
    password: uqhuazejniqxdceg
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false