spring:
  datasource:
    url: jdbc:postgresql://dpg-ckig980mccbs738ohefg-a.oregon-postgres.render.com/erp_database_render
    username: erp_database_render_user
    password: kraF6uilCMBlK8PE7uNZPqDP6S6PKzGp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


